[package]
name = "afwdist"
version = "1.0.0"
edition = "2024"

[dependencies]
assert_approx_eq = "1.1.0"
bio = "2.2.0"
clap = { version = "4.5.7", features = ["derive"] }
csv = "1.3.1"
itertools = "0.14.0"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
simplelog = "0.12.2"
